# This is a sample build configuration for C++ â€“ Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: gcc:6.5

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          #  Install a CMake 3.0.2 version.
          #- apt-get update -qq
          #- apt-get install cmake -y
          #  Alternatively you could install a CMake 3.2.2 version through PPA repository. 
          - apt-get update -qq
          - apt-get install software-properties-common -y
          # Add PPA repository.
          - echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/cmake.list
          - apt-get update -qq
          - apt-get install cmake -y --force-yes
          - mkdir code
          - cd code
          - git clone https://github.com/nlohmann/json.git
          - cd json
          - mkdir -p build
          - cd build
          - cmake .. -DJSON_BuildTests=OFF
          - make
          - make install
          - cd ../..
          - rm -rf code
          - mkdir build
          - cd build
          - cmake .. 
          - make
